/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-error-container": "#93000a",
        "tertiary-fixed": "#ffdf93",
        "background": "#fbf9f6",
        "tertiary": "#765b00",
        "error-container": "#ffdad6",
        "secondary-container": "#fdc756",
        "on-tertiary": "#ffffff",
        "surface-variant": "#e4e2df",
        "on-tertiary-fixed": "#241a00",
        "surface-bright": "#fbf9f6",
        "inverse-surface": "#30312f",
        "on-primary-container": "#858481",
        "on-secondary-fixed-variant": "#5d4200",
        "on-primary-fixed-variant": "#474744",
        "surface-container": "#efeeeb",
        "secondary": "#7b5900",
        "on-primary": "#ffffff",
        "surface-tint": "#5f5e5c",
        "inverse-primary": "#c9c6c3",
        "primary": "#000000",
        "secondary-fixed-dim": "#f4be4e",
        "error": "#ba1a1a",
        "on-primary-fixed": "#1c1c1a",
        "inverse-on-surface": "#f2f0ed",
        "surface-container-low": "#f5f3f0",
        "surface-container-lowest": "#ffffff",
        "on-secondary-container": "#725200",
        "on-tertiary-fixed-variant": "#594400",
        "on-secondary-fixed": "#261900",
        "on-secondary": "#ffffff",
        "secondary-fixed": "#ffdea4",
        "on-tertiary-container": "#503d00",
        "tertiary-fixed-dim": "#edc14a",
        "on-background": "#1b1c1a",
        "primary-fixed-dim": "#c9c6c3",
        "outline-variant": "#c8c7bf",
        "on-surface": "#1b1c1a",
        "tertiary-container": "#cfa630",
        "on-surface-variant": "#474741",
        "surface-dim": "#dbdad7",
        "on-error": "#ffffff",
        "outline": "#777771",
        "primary-container": "#1c1c1a",
        "surface-container-high": "#eae8e5",
        "primary-fixed": "#e5e2de",
        "surface-container-highest": "#e4e2df",
        "surface": "#fbf9f6"
      },
      borderRadius: {
        DEFAULT: "1rem",
        lg: "2rem",
        xl: "3rem",
        full: "9999px"
      },
      spacing: {
        "space-3xl": "3.5rem",
        "layout-margin-tablet": "1.5rem",
        "layout-margin-desktop": "2.5rem",
        "space-lg": "1.5rem",
        "space-2xl": "2.5rem",
        "space-sm": "0.75rem",
        "grid-gutter": "1.25rem",
        "space-xs": "0.5rem",
        "layout-margin-mobile": "1rem",
        "space-md": "1rem",
        "space-2xs": "0.25rem",
        "space-xl": "2rem"
      },
      fontFamily: {
        "headline-lg": ["Plus Jakarta Sans", "sans-serif"],
        "body-md": ["Plus Jakarta Sans", "sans-serif"],
        "display-hero-mobile": ["Plus Jakarta Sans", "sans-serif"],
        "body-lg": ["Plus Jakarta Sans", "sans-serif"],
        "label-caps-micro": ["Space Grotesk", "sans-serif"],
        "label-code-md": ["Space Grotesk", "sans-serif"],
        "headline-md": ["Plus Jakarta Sans", "sans-serif"],
        "headline-sm": ["Plus Jakarta Sans", "sans-serif"],
        "headline-lg-mobile": ["Plus Jakarta Sans", "sans-serif"],
        "body-sm": ["Plus Jakarta Sans", "sans-serif"],
        "label-code-lg": ["Space Grotesk", "sans-serif"],
        "display-hero": ["Plus Jakarta Sans", "sans-serif"]
      },
      fontSize: {
        "headline-lg": ["30px", { lineHeight: "38px", letterSpacing: "-0.025em", fontWeight: "400" }],
        "body-md": ["13px", { lineHeight: "20px", letterSpacing: "0em", fontWeight: "400" }],
        "display-hero-mobile": ["32px", { lineHeight: "38px", letterSpacing: "-0.02em", fontWeight: "500" }],
        "body-lg": ["15px", { lineHeight: "24px", letterSpacing: "-0.005em", fontWeight: "400" }],
        "label-caps-micro": ["10px", { lineHeight: "12px", letterSpacing: "0.08em", fontWeight: "700" }],
        "label-code-md": ["12px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "500" }],
        "headline-md": ["22px", { lineHeight: "28px", letterSpacing: "-0.015em", fontWeight: "500" }],
        "headline-sm": ["17px", { lineHeight: "22px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-lg-mobile": ["24px", { lineHeight: "30px", letterSpacing: "-0.015em", fontWeight: "500" }],
        "body-sm": ["12px", { lineHeight: "17px", letterSpacing: "0.01em", fontWeight: "400" }],
        "label-code-lg": ["14px", { lineHeight: "18px", letterSpacing: "0.01em", fontWeight: "600" }],
        "display-hero": ["44px", { lineHeight: "52px", letterSpacing: "-0.03em", fontWeight: "400" }]
      }
    }
  },
  plugins: [],
}
