import { useEffect, useMemo, useState } from "react";
import { Link } from "react-router-dom";
import { Activity, AlertTriangle, ChevronRight, Clock3, Eye, MapPin, Radar } from "lucide-react";
import { fetchRoute } from "../services/api";
import type { RouteSegment } from "../types/route";

const shell = "w-full max-w-[1440px] mx-auto px-layout-margin-mobile md:px-layout-margin-tablet lg:px-layout-margin-desktop";
const color = (score: number) => score >= 75 ? "#B93535" : score >= 50 ? "#D36128" : score >= 30 ? "#D99B26" : "#2E7D5B";

export default function LiveAnalyticsRiskHeatmap() {
  const [segments, setSegments] = useState<RouteSegment[]>([]);
  const [filter, setFilter] = useState<"all" | "hazards" | "surface">("all");
  useEffect(() => { document.title = "LIVE ANALYTICS & RISK HEATMAP | SafeRoute Telangana"; fetchRoute().then(setSegments); }, []);
  const filtered = useMemo(() => segments.filter(item => filter === "all" || filter === "hazards" ? filter === "all" || item.waterlogging_flag || item.news_flags?.length : item.vision_severity !== "none"), [segments, filter]);
  const average = segments.length ? Math.round(segments.reduce((sum, item) => sum + item.final_score, 0) / segments.length) : 0;
  const signals = segments.filter(item => item.waterlogging_flag || item.news_flags?.length).length;
  const hourlyRisk = useMemo(() => Array.from({ length: 12 }, (_, index) => {
    const hour = index * 2;
    const commuterLift = hour >= 16 && hour <= 20 ? 18 : hour >= 6 && hour <= 10 ? 10 : 0;
    const weatherLift = segments.filter(item => item.waterlogging_flag).length * 4;
    return { hour, score: Math.min(100, Math.max(8, average + commuterLift + weatherLift - Math.abs(12 - hour))) };
  }), [average, segments]);
  return <div className="pt-20 pb-space-3xl min-h-screen bg-background"><div className={`${shell} pt-space-xl`}>
    <div className="flex flex-col lg:flex-row lg:justify-between lg:items-end gap-space-lg"><div><span className="font-label-caps-micro text-secondary uppercase">Route analytics workspace</span><h1 className="font-headline-lg mt-space-xs">LIVE ANALYTICS &amp; RISK HEATMAP</h1><p className="font-body-md text-on-surface-variant mt-space-xs max-w-2xl">A spatial summary of the loaded route data. Live GIS and camera feeds require a backend endpoint and are shown only when supplied.</p></div><div className="inline-flex self-start p-1 rounded-full bg-surface-container-low border border-surface-variant">{([['all','All signals'],['hazards','Hazards'],['surface','Vision']] as const).map(([value,label]) => <button key={value} onClick={() => setFilter(value)} className={`px-space-md py-space-xs rounded-full font-body-sm ${filter === value ? "bg-on-surface text-surface" : "text-on-surface-variant"}`}>{label}</button>)}</div></div>
    <div className="grid grid-cols-2 lg:grid-cols-4 gap-space-md mt-space-xl"><Metric icon={<Radar/>} label="Mapped corridors" value={segments.length} note="Loaded route segments"/><Metric icon={<Activity/>} label="Mean composite risk" value={`${average}/100`} note="Fused score average"/><Metric icon={<AlertTriangle/>} label="Hazard signals" value={signals} note="News or inundation flags"/><Metric icon={<Eye/>} label="Vision detections" value={segments.filter(item => item.vision_severity !== "none").length} note="Route adapter imagery"/></div>
    <div className="grid grid-cols-1 lg:grid-cols-12 gap-space-lg mt-space-xl"><section className="lg:col-span-8 rounded-[1.75rem] bg-surface-container-lowest border border-surface-variant p-space-lg shadow-sm"><div className="flex justify-between items-start gap-space-md"><div><span className="font-label-caps-micro uppercase text-secondary">Geo-spatial risk matrix</span><h2 className="font-headline-md mt-space-xs">Corridor heatmap</h2></div><span className="font-body-sm text-on-surface-variant">Visualization based on segment midpoints</span></div><div className="relative h-[420px] rounded-xl mt-space-lg overflow-hidden bg-[#E9E6DE] bg-[linear-gradient(120deg,transparent_0%,rgba(255,255,255,.7)_48%,transparent_49%),linear-gradient(20deg,transparent_0%,rgba(255,255,255,.65)_48%,transparent_49%)]"><div className="absolute inset-0 opacity-40" style={{backgroundImage:"radial-gradient(#a7a298 1px, transparent 1px)", backgroundSize:"18px 18px"}}/>{filtered.map((item, index) => <Link key={item.segment_id} to={`/segment/${item.segment_id}`} aria-label={`View ${item.road_name} diagnostics`} className="absolute group" style={{left:`${18 + ((item.midpoint.lng * 13 + index * 19) % 63)}%`, top:`${16 + ((item.midpoint.lat * 17 + index * 23) % 62)}%`}}><span className="absolute -inset-5 rounded-full opacity-20 animate-ping" style={{backgroundColor: color(item.final_score)}}/><span className="relative flex w-9 h-9 rounded-full items-center justify-center border-4 border-white shadow-lg text-white" style={{backgroundColor:color(item.final_score)}}><MapPin size={16}/></span><span className="absolute left-5 top-5 min-w-40 p-space-xs bg-surface-container-lowest rounded text-on-surface text-xs shadow opacity-0 group-hover:opacity-100 transition-opacity">{item.road_name} · {item.final_score}/100</span></Link>)}<div className="absolute bottom-4 left-4 p-space-xs rounded-lg bg-surface-container-lowest/90 font-body-sm shadow">No live map tiles connected · plotted from loaded segment coordinates</div></div></section>
    <aside className="lg:col-span-4 rounded-[1.75rem] bg-surface-container-lowest border border-surface-variant p-space-lg shadow-sm"><span className="font-label-caps-micro uppercase text-secondary">Risk distribution</span><h2 className="font-headline-md mt-space-xs">Score profile</h2><div className="mt-space-lg flex items-end gap-space-sm h-52">{segments.map(item => <Link key={item.segment_id} to={`/segment/${item.segment_id}`} className="flex-1 h-full flex flex-col justify-end group"><span className="text-center font-label-caps-micro mb-space-xs opacity-0 group-hover:opacity-100">{item.final_score}</span><span className="rounded-t-md min-h-2 transition-opacity group-hover:opacity-70" style={{height:`${Math.max(8,item.final_score)}%`, backgroundColor:color(item.final_score)}}/></Link>)}</div><div className="grid grid-cols-2 gap-space-xs mt-space-lg font-body-sm"><span className="inline-flex items-center gap-space-xs"><i className="w-2 h-2 rounded-full bg-[#2E7D5B]"/>Low</span><span className="inline-flex items-center gap-space-xs"><i className="w-2 h-2 rounded-full bg-[#D99B26]"/>Moderate</span><span className="inline-flex items-center gap-space-xs"><i className="w-2 h-2 rounded-full bg-[#D36128]"/>High</span><span className="inline-flex items-center gap-space-xs"><i className="w-2 h-2 rounded-full bg-[#B93535]"/>Severe</span></div></aside></div>
    <div className="grid grid-cols-1 lg:grid-cols-12 gap-space-lg mt-space-xl"><section className="lg:col-span-7 rounded-[1.75rem] bg-surface-container-lowest border border-surface-variant p-space-lg shadow-sm"><div className="flex justify-between gap-space-md"><div><span className="font-label-caps-micro uppercase text-secondary">AI-calibrated forecast</span><h2 className="font-headline-md mt-space-xs">Diurnal risk distribution curve</h2></div><span className="font-body-sm text-on-surface-variant">Derived from loaded risk, time bands and inundation flags</span></div><div className="h-52 mt-space-lg flex items-end gap-2 border-b border-surface-variant">{hourlyRisk.map(point => <div key={point.hour} className="group flex-1 h-full flex flex-col justify-end items-center"><span className="font-label-caps-micro opacity-0 group-hover:opacity-100 mb-space-2xs">{point.score}</span><span className="w-full rounded-t-md bg-secondary-container group-hover:bg-secondary transition-colors" style={{height:`${point.score}%`}}/><span className="font-body-sm text-on-surface-variant mt-space-xs">{String(point.hour).padStart(2, "0")}</span></div>)}</div></section><aside className="lg:col-span-5 rounded-[1.75rem] bg-surface-container-lowest border border-surface-variant p-space-lg shadow-sm"><span className="font-label-caps-micro uppercase text-secondary">Detection feed</span><h2 className="font-headline-md mt-space-xs">Automated telemetry events</h2><div className="mt-space-md divide-y divide-surface-variant">{segments.slice().sort((a,b)=>b.final_score-a.final_score).map(item => <Link key={item.segment_id} to={`/segment/${item.segment_id}`} className="py-space-sm flex gap-space-sm hover:bg-surface-container-low transition-colors"><span className="w-7 h-7 shrink-0 flex items-center justify-center rounded-full bg-surface-container text-secondary"><Clock3 size={14}/></span><span><b className="font-body-sm">{item.road_name}</b><span className="block font-body-sm text-on-surface-variant">{item.news_flags?.[0] ?? `${item.vision_severity} surface assessment recorded`} · Risk {item.final_score}/100</span></span><ChevronRight size={15} className="ml-auto mt-1 text-on-surface-variant"/></Link>)}</div></aside></div>
    <section className="mt-space-xl rounded-[1.75rem] bg-surface-container-low p-space-lg"><div className="flex justify-between items-center gap-space-md"><div><span className="font-label-caps-micro uppercase text-secondary">Signal inventory</span><h2 className="font-headline-md mt-space-xs">Segment telemetry</h2></div><span className="font-body-sm text-on-surface-variant">Click a row for the full AI breakdown</span></div><div className="grid grid-cols-1 md:grid-cols-2 gap-space-sm mt-space-lg">{filtered.map(item => <Link key={item.segment_id} to={`/segment/${item.segment_id}`} className="bg-surface-container-lowest rounded-xl p-space-md flex justify-between gap-space-md hover:bg-secondary-container/20 transition-colors"><div><div className="flex gap-space-xs items-center"><span className="w-2 h-2 rounded-full" style={{backgroundColor:color(item.final_score)}}/><h3 className="font-body-md font-semibold">{item.road_name}</h3></div><p className="font-body-sm text-on-surface-variant mt-space-xs">{item.waterlogging_flag ? "Inundation flag" : "No inundation flag"} · {item.vision_severity} vision severity · {item.traffic_level} traffic</p></div><span className="flex items-center gap-space-xs font-label-code-md" style={{color:color(item.final_score)}}>{item.final_score}/100 <ChevronRight size={15}/></span></Link>)}</div>{!filtered.length && <div className="p-space-lg text-center font-body-sm text-on-surface-variant">No segments match this filter.</div>}</section>
  </div></div>;
}
function Metric({icon,label,value,note}:{icon:React.ReactNode;label:string;value:string|number;note:string}) { return <article className="p-space-lg rounded-xl bg-surface-container-lowest border border-surface-variant shadow-sm"><div className="flex justify-between text-secondary"><span className="font-label-caps-micro uppercase">{label}</span>{icon}</div><div className="text-4xl mt-space-lg">{value}</div><p className="font-body-sm text-on-surface-variant mt-space-xs">{note}</p></article>; }
