//frontend/src/pages/RealTimeHazardRerouteAdvisory.tsx
import { useEffect, useMemo, useState } from "react";
import { Link, useNavigate } from "react-router-dom";
import { AlertTriangle, ArrowRight, Check, ChevronLeft, CloudRain, MapPin, Navigation, Radio, ShieldCheck, Volume2 } from "lucide-react";
import type { RouteSegment } from "../types/route";
import { useRouteContext } from "../context/RouteContext";

const shell = "w-full max-w-[1440px] mx-auto px-layout-margin-mobile md:px-layout-margin-tablet lg:px-layout-margin-desktop";
const risk = (score: number) => score >= 75 ? "text-[#B93535] bg-[#F9EAEA] border-[#B93535]/20" : score >= 50 ? "text-[#D36128] bg-[#FAEEE8] border-[#D36128]/20" : "text-[#2E7D5B] bg-[#EBF4EF] border-[#2E7D5B]/20";

export default function RealTimeHazardRerouteAdvisory() {
  const { routeData } = useRouteContext();
  const segments = routeData?.segments ?? [];
  const [accepted, setAccepted] = useState(false);
  const [voiceOn, setVoiceOn] = useState(false);
  const navigate = useNavigate();
  useEffect(() => { document.title = "REAL-TIME HAZARD & REROUTE ADVISORY | SafeRoute Telangana"; }, []);
  const direct = useMemo(() => segments.reduce<RouteSegment | null>((worst, item) => !worst || item.final_score > worst.final_score ? item : worst, null), [segments]);
  const safer = useMemo(() => segments.reduce<RouteSegment | null>((best, item) => !best || item.final_score < best.final_score ? item : best, null), [segments]);
  const delay = direct ? Math.max(4, Math.round(direct.final_score / 3)) : 0;

  if (!direct || !safer) return <div className="pt-20 min-h-screen bg-background"><div className={`${shell} pt-space-2xl`}><div className="bg-surface-container-lowest rounded-xl p-space-xl">Evaluating available route signals…</div></div></div>;
  return <div className="pt-20 min-h-screen bg-surface-container relative overflow-hidden">
    <div className="absolute inset-0 opacity-60 bg-[radial-gradient(circle_at_25%_20%,rgba(253,199,86,.32),transparent_25%),radial-gradient(circle_at_80%_48%,rgba(185,53,53,.16),transparent_28%)]" />
    <div className={`${shell} relative py-space-xl md:py-space-2xl`}>
      <div className="flex flex-wrap justify-between gap-space-sm font-body-sm text-on-surface-variant mb-space-md"><Link to="/route" className="inline-flex gap-space-xs items-center hover:text-on-surface"><ChevronLeft size={16}/> Back to route results</Link><span>Source: route adapter · no dispatch endpoint exposed</span></div>
      <section className="max-w-[1120px] mx-auto rounded-[2rem] overflow-hidden border border-surface-variant bg-surface-container-lowest shadow-[0_24px_48px_-8px_rgba(26,26,24,.14)]">
        <div className="bg-[#C92325] text-white px-space-lg py-space-xs font-label-caps-micro uppercase flex justify-between gap-space-md"><span className="inline-flex items-center gap-space-xs"><Radio size={13}/> Live hazard intercept · route safety review</span><span className="hidden sm:inline">Route advisory active</span></div>
        <div className="p-space-lg md:p-space-xl">
          <div className="flex flex-col md:flex-row md:justify-between gap-space-lg"><div><span className="inline-flex px-space-sm py-space-2xs bg-[#F9EAEA] text-[#B93535] rounded-full font-label-caps-micro uppercase">Critical dynamic blackspot</span><h1 className="font-headline-lg mt-space-sm max-w-2xl">REAL-TIME HAZARD &amp; REROUTE ADVISORY</h1><p className="font-body-md text-on-surface-variant mt-space-xs">Highest current risk is concentrated at {direct.road_name}. The recommendation below is recomputed from the loaded route segments.</p><div className="flex items-center gap-space-xs mt-space-md font-body-sm"><MapPin size={16} className="text-[#B93535]"/> {direct.road_name} <span className="text-secondary">• {direct.midpoint.lat.toFixed(4)}, {direct.midpoint.lng.toFixed(4)}</span></div></div><div className={`min-w-44 self-start p-space-md rounded-xl border ${risk(direct.final_score)}`}><span className="font-label-caps-micro uppercase block">Severity level</span><div className="flex items-end gap-space-xs mt-space-xs"><strong className="text-4xl">{direct.final_score}</strong><span className="font-body-sm mb-1">/100</span></div><span className="font-body-sm">AI risk score</span></div></div>
          <div className="mt-space-lg"><div className="flex justify-between items-center font-label-caps-micro uppercase text-on-surface-variant"><span>Triangulated multi-modal telemetry</span><span className="text-secondary">{[direct.waterlogging_flag, direct.news_flags?.length, direct.vision_severity !== "none"].filter(Boolean).length} verified signals</span></div><div className="grid grid-cols-1 md:grid-cols-3 gap-space-md mt-space-sm">
            <Signal icon={<CloudRain size={18}/>} title="Drainage & weather" value={direct.waterlogging_flag ? "Waterlogging detected" : "No inundation flag"} detail={direct.waterlogging_flag ? "Environmental risk modifier is active for this segment." : "No live weather endpoint is available."} tone={direct.waterlogging_flag ? "text-[#B93535]" : "text-[#2E7D5B]"}/>
            <Signal icon={<Navigation size={18}/>} title="Traffic & route state" value={`${direct.traffic_level} traffic`} detail={`Historical risk score: ${direct.historical_score}/100. Current traffic is retained from the route adapter.`} tone="text-secondary"/>
            <Signal icon={<AlertTriangle size={18}/>} title="Incident & vision" value={direct.news_flags?.[0] ?? `${direct.vision_severity} surface signal`} detail={direct.news_flags?.length ? "Incident headline is attached to the loaded route data." : "No local incident headline is attached."} tone={direct.news_flags?.length ? "text-[#B93535]" : "text-secondary"}/>
          </div></div>
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-space-lg mt-space-xl"><article className="rounded-[1.75rem] bg-surface-container-low p-space-lg border-t-4 border-[#B93535]"><div className="flex justify-between gap-space-sm"><div><span className="font-label-caps-micro text-[#B93535] uppercase">Current route · hazard impending</span><h2 className="font-headline-md mt-space-xs">{direct.road_name}</h2><p className="font-body-sm text-on-surface-variant">Direct route segment with the highest fused risk score.</p></div><span className="font-label-caps-micro text-[#B93535]">RISK: {direct.final_score}/100</span></div><div className="mt-space-md h-2 rounded-full bg-[#F2D3D3]"><div className="h-full rounded-full bg-[#B93535]" style={{width:`${direct.final_score}%`}}/></div><div className="mt-space-md p-space-md rounded-xl bg-surface-container-lowest"><div className="flex justify-between"><span className="font-body-sm text-on-surface-variant">Estimated travel impact</span><b className="text-[#B93535]">+{delay} mins</b></div><p className="font-body-sm text-on-surface-variant mt-space-xs">{direct.explanation}</p></div><button onClick={() => navigate(`/segment/${direct.segment_id}`)} className="mt-space-md w-full py-space-sm rounded-full bg-surface-container-high font-body-sm hover:bg-surface-container">Inspect risk breakdown</button></article>
          <article className="rounded-[1.75rem] bg-surface-container-lowest p-space-lg border-t-4 border-secondary shadow-sm"><div className="flex justify-between gap-space-sm"><div><span className="inline-flex items-center gap-space-2xs font-label-caps-micro text-secondary uppercase"><ShieldCheck size={14}/> SafeRoute recommended</span><h2 className="font-headline-md mt-space-xs">Via {safer.road_name}</h2><p className="font-body-sm text-on-surface-variant">Lowest-risk alternative among the available route segments.</p></div><span className="font-label-caps-micro text-[#2E7D5B]">RISK: {safer.final_score}/100</span></div><div className="mt-space-md h-2 rounded-full bg-surface-container"><div className="h-full rounded-full bg-secondary-container" style={{width:`${Math.max(8, safer.final_score)}%`}}/></div><div className="mt-space-md p-space-md rounded-xl bg-surface-container-low"><div className="flex justify-between"><span className="font-body-sm text-on-surface-variant">Projected reroute time</span><b>{40 + Math.round(safer.final_score / 3)} mins</b></div><div className="grid grid-cols-2 gap-space-xs mt-space-sm font-body-sm text-on-surface-variant"><span><Check size={14} className="inline text-[#2E7D5B]"/> Lower risk</span><span><Check size={14} className="inline text-[#2E7D5B]"/> Route data verified</span><span><Check size={14} className="inline text-[#2E7D5B]"/> Fewer hazards</span><span><Check size={14} className="inline text-[#2E7D5B]"/> Safer surface</span></div></div><button onClick={() => { setAccepted(true); navigate(`/segment/${safer.segment_id}`); }} className="mt-space-md w-full py-space-sm rounded-full bg-secondary-container text-on-secondary-container font-body-md font-semibold inline-flex items-center justify-center gap-space-xs">Accept safer reroute <ArrowRight size={17}/></button></article></div>
          <div className="mt-space-lg p-space-md rounded-xl bg-surface-container-low flex flex-col sm:flex-row sm:items-center justify-between gap-space-sm"><button onClick={() => setVoiceOn(!voiceOn)} className="font-body-sm inline-flex items-center gap-space-xs"><span className={`w-8 h-5 rounded-full p-0.5 ${voiceOn ? "bg-secondary" : "bg-outline-variant"}`}><span className={`block w-4 h-4 rounded-full bg-white transition-transform ${voiceOn ? "translate-x-3" : ""}`}/></span><Volume2 size={15}/> Voice advisory {voiceOn ? "enabled" : "disabled"}</button><span className="font-body-sm text-on-surface-variant">{accepted ? "Reroute accepted — opening segment diagnostics." : "Recommendation is ready for driver review."}</span></div>
        </div>
      </section>
    </div>
  </div>;
}

function Signal({ icon, title, value, detail, tone }: { icon: React.ReactNode; title: string; value: string; detail: string; tone: string }) { return <article className="p-space-md rounded-xl bg-surface-container-low"><div className={`inline-flex items-center gap-space-xs ${tone}`}><span>{icon}</span><span className="font-label-caps-micro uppercase">{title}</span></div><h3 className="font-body-md font-semibold mt-space-sm">{value}</h3><p className="font-body-sm text-on-surface-variant mt-space-xs">{detail}</p></article>; }
