import { Link, useNavigate, useParams } from "react-router-dom";
import { useEffect, useMemo, useState } from "react";
import { AlertTriangle, ArrowLeft, ArrowRight, MapPin, ShieldCheck, Volume2, X } from "lucide-react";
import { fetchRoute } from "../services/api";
import type { RouteSegment } from "../types/route";

const shell = "w-full max-w-[1440px] mx-auto px-layout-margin-mobile md:px-layout-margin-tablet lg:px-layout-margin-desktop";
const scoreTone = (score: number) => score >= 75 ? "text-[#B93535] bg-[#F9EAEA]" : score >= 50 ? "text-[#D36128] bg-[#FAEEE8]" : score >= 30 ? "text-[#D99B26] bg-[#FAF4E6]" : "text-[#2E7D5B] bg-[#EBF4EF]";

function useSegments() {
  const [segments, setSegments] = useState<RouteSegment[]>([]);
  useEffect(() => { fetchRoute().then(setSegments); }, []);
  return segments;
}

export function SegmentDiagnostics() {
  const segments = useSegments(); const { segmentId } = useParams(); const navigate = useNavigate(); const [index, setIndex] = useState(0);
  useEffect(() => { document.title = "Segment AI Diagnostics & Risk Breakdown | SafeRoute Telangana"; }, []);
  useEffect(() => { const found = segments.findIndex(item => item.segment_id === segmentId); if (found >= 0) setIndex(found); }, [segmentId, segments]);
  const segment = segments[index] ?? null;
  const factors = segment ? [
    ["IIT Delhi crash history", segment.historical_score, "25%"],
    ["YOLOv8 road surface", segment.vision_severity === "severe" ? 80 : segment.vision_severity === "moderate" ? 55 : segment.vision_severity === "minor" ? 30 : 0, "35%"],
    ["Weather & inundation", segment.weather_modifier + (segment.waterlogging_flag ? 25 : 0), "20%"],
    ["News & police dispatch", segment.news_flags?.length ? 40 : 0, "20%"],
  ] : [];
  return <div className="pt-20 pb-space-3xl bg-background min-h-screen"><div className={`${shell} pt-space-xl`}>
    <div className="flex justify-between items-center gap-space-md mb-space-lg font-body-sm text-on-surface-variant"><Link to="/route" className="flex shrink-0 gap-space-xs items-center"><ArrowLeft size={16}/> Route results</Link><span className="text-right">Segment AI Diagnostics &amp; Risk Breakdown / {segment?.segment_id ?? "Analyzing"}</span></div>
    {!segment ? <div className="p-space-xl bg-surface-container-low rounded-xl">Analyzing available route segments…</div> : <>
      <section className="bg-surface-container-lowest rounded-xl p-space-xl shadow-sm border border-surface-variant flex flex-col md:flex-row justify-between gap-space-lg mb-space-lg"><div><span className="font-label-caps-micro text-label-caps-micro text-secondary uppercase">Route adapter data · current segment</span><h1 className="font-headline-lg text-headline-lg mt-space-xs">{segment.road_name}</h1><p className="font-body-md text-on-surface-variant mt-space-xs">Segment ID: {segment.segment_id} · {segment.traffic_level} traffic · {segment.waterlogging_flag ? "waterlogging flagged" : "drainage clear"}</p><div className="flex flex-wrap gap-x-space-md gap-y-space-xs mt-space-md font-body-sm text-on-surface-variant"><span>Lat {segment.midpoint.lat.toFixed(4)}</span><span>Lng {segment.midpoint.lng.toFixed(4)}</span><span>Road scan: {segment.vision_severity}</span></div></div><div className={`w-32 h-32 shrink-0 border-[8px] border-current rounded-full flex flex-col items-center justify-center ${scoreTone(segment.final_score)}`}><b className="text-4xl">{segment.final_score}</b><span className="font-label-caps-micro uppercase">/ 100 · {segment.final_score >= 30 ? "moderate" : "low"}</span></div></section>
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-space-lg"><section className="lg:col-span-7 bg-surface-container-lowest rounded-xl p-space-lg shadow-sm"><h2 className="font-headline-sm">Multi-Factor Risk Decomposition</h2><div className="mt-space-lg flex flex-col gap-space-md">{factors.map(([name, value, weight]) => <div key={String(name)}><div className="flex justify-between font-body-sm"><span>{name}</span><b>{value}/100 · {weight}</b></div><div className="h-2.5 bg-surface-container rounded-full mt-space-xs"><div className="h-full rounded-full bg-secondary-container" style={{width:`${Math.min(Number(value),100)}%`}}/></div></div>)}</div></section>
      <aside className="lg:col-span-5 bg-surface-container-lowest rounded-xl p-space-lg shadow-sm"><h2 className="font-headline-sm">Synthesized Safety Narrative</h2><p className="font-body-md text-on-surface-variant mt-space-md leading-relaxed">{segment.explanation} Historical, surface, environmental, and incident signals are combined by the existing risk pipeline.</p><div className="mt-space-lg p-space-md rounded-DEFAULT bg-surface-container-low font-body-sm">Source status: local route pipeline fallback. No live API endpoint is currently exposed.</div></aside></div>
      <section className="mt-space-lg bg-surface-container-lowest rounded-xl p-space-lg shadow-sm"><div className="flex flex-col sm:flex-row justify-between sm:items-center gap-space-md"><div><h2 className="font-headline-sm">YOLOv8 Street-Level Detection Visualizer</h2><p className="font-body-sm text-on-surface-variant">{segment.image_source === "rdd2022_sample" ? "Representative RDD2022 training image — fallback, not live Mapillary coverage." : segment.image_source === "site" ? "Route-attached road image. Source metadata is retained from the route adapter." : "Mapillary coverage and an inference frame are unavailable for this segment."}</p></div><span className="font-label-caps-micro uppercase text-secondary">{segment.image_source ? "Fallback / local source" : "Vision unavailable"}</span></div>{segment.image_url ? <div className="relative mt-space-md"><img src={segment.image_url} alt="Road surface source" className="w-full h-80 object-cover rounded-lg"/><div className="absolute inset-x-4 sm:inset-x-8 bottom-4 sm:bottom-8 border-2 border-secondary rounded p-space-xs text-secondary font-label-caps-micro bg-on-surface/80">YOLOv8 INPUT FRAME · {segment.vision_severity.toUpperCase()} SURFACE SIGNAL</div></div> : <div className="mt-space-md h-64 rounded-lg bg-surface-container flex flex-col gap-space-xs items-center justify-center text-on-surface-variant"><span>Vision scan unavailable</span><span className="font-body-sm">No result was fabricated for this segment.</span></div>}</section>
      <section className="mt-space-lg"><div className="flex flex-col sm:flex-row sm:items-end justify-between gap-space-sm"><div><span className="font-label-caps-micro uppercase text-secondary">Route context</span><h2 className="font-headline-sm mt-space-xs">Adjacent Corridor Risk Trajectory</h2></div><p className="font-body-sm text-on-surface-variant">Select any corridor to refresh the entire diagnostic breakdown.</p></div><div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-space-md mt-space-md">{segments.map((item, itemIndex) => <button key={item.segment_id} onClick={() => navigate(`/segment/${item.segment_id}`)} className={`text-left rounded-xl p-space-md border transition-colors ${itemIndex === index ? "border-secondary bg-secondary-container/20" : "border-surface-variant bg-surface-container-lowest hover:bg-surface-container-low"}`}><span className="font-label-caps-micro uppercase text-on-surface-variant">Segment {String(itemIndex + 1).padStart(2, "0")}</span><div className="flex items-start justify-between gap-space-sm mt-space-xs"><span className="font-body-md">{item.road_name}</span><b className={scoreTone(item.final_score).split(" ")[0]}>{item.final_score}</b></div><span className="font-body-sm text-on-surface-variant mt-space-xs block">{item.waterlogging_flag ? "Inundation signal" : `${item.vision_severity} surface signal`}</span></button>)}</div></section>
      <div className="mt-space-lg flex justify-between"><button onClick={()=>segments[index-1] && navigate(`/segment/${segments[index-1].segment_id}`)} disabled={!index} className="btn btn-outline"><ArrowLeft size={16}/> Previous</button><button onClick={()=>segments[index+1] && navigate(`/segment/${segments[index+1].segment_id}`)} disabled={index===segments.length-1} className="btn btn-primary">Next <ArrowRight size={16}/></button></div>
    </>}</div></div>;
}

export function HazardAdvisory() { const navigate=useNavigate(); const segments=useSegments(); const severe=segments.find(s=>s.final_score>=75) ?? segments[0]; const safe=segments.find(s=>s.final_score<30) ?? segments[0]; return <div className="pt-20 min-h-screen bg-surface-container"><div className={`${shell} py-space-3xl`}><section className="max-w-5xl mx-auto bg-surface-container-lowest rounded-xl overflow-hidden shadow-xl"><div className="bg-error text-on-error px-space-lg py-space-xs font-label-caps-micro uppercase">Live hazard intercept · simulation from local route data</div><div className="p-space-xl"><button onClick={()=>navigate('/route')} className="float-right text-on-surface-variant"><X/></button><span className="font-label-caps-micro text-error uppercase">Critical dynamic blackspot</span><h1 className="font-headline-lg mt-space-xs">Route hazard advisory</h1><p className="font-body-md text-on-surface-variant mt-space-xs">A severe segment requires a safer-routing decision.</p><div className="grid grid-cols-1 md:grid-cols-2 gap-space-lg mt-space-xl"><div className="p-space-lg rounded-xl bg-[#F9EAEA]"><AlertTriangle className="text-error"/><h2 className="font-headline-md mt-space-sm">Current route: {severe?.road_name}</h2><b className="text-error text-3xl">{severe?.final_score}/100</b><p className="font-body-sm mt-space-sm">{severe?.explanation}</p><button className="btn btn-outline mt-space-md w-full">Continue current route</button></div><div className="p-space-lg rounded-xl bg-[#EBF4EF]"><ShieldCheck className="text-[#2E7D5B]"/><h2 className="font-headline-md mt-space-sm">SafeRoute alternative: {safe?.road_name}</h2><b className="text-[#2E7D5B] text-3xl">{safe?.final_score}/100</b><p className="font-body-sm mt-space-sm">Uses the existing route result data; route switching is staged in frontend state.</p><button onClick={()=>navigate('/route')} className="btn btn-primary mt-space-md w-full">Accept safer reroute</button></div></div><div className="mt-space-lg font-body-sm text-on-surface-variant flex gap-space-sm"><Volume2 size={18}/> Voice advisory ready; no voice service is connected.</div></div></section></div></div>; }

export function Analytics() { const segments=useSegments(); const [mode,setMode]=useState<"Live"|"Simulation">("Simulation"); const average=useMemo(()=>segments.length?Math.round(segments.reduce((n,s)=>n+s.final_score,0)/segments.length):0,[segments]); return <div className="pt-20 pb-space-3xl bg-background min-h-screen"><div className={`${shell} pt-space-xl`}><div className="flex justify-between items-center flex-wrap gap-space-md"><div><span className="font-label-caps-micro text-secondary uppercase">Telemetry mode: {mode}</span><h1 className="font-headline-lg mt-space-xs">Telangana Mobility Risk & Computer Vision Telemetry</h1></div><div className="flex bg-surface-container-low p-1 rounded-full">{(["Live","Simulation"] as const).map(item=><button key={item} onClick={()=>setMode(item)} className={`px-space-md py-space-xs rounded-full font-body-sm ${mode===item?"bg-on-surface text-surface":""}`}>{item}</button>)}</div></div><div className="grid grid-cols-2 lg:grid-cols-4 gap-space-md mt-space-xl">{[["Mapped corridors",segments.length],["Average risk",`${average}/100`],["Surface anomalies",segments.filter(s=>s.vision_severity!=="none").length],["Hazard signals",segments.filter(s=>s.news_flags?.length||s.waterlogging_flag).length]].map(([name,value])=><div key={String(name)} className="p-space-lg bg-surface-container-lowest rounded-xl shadow-sm"><span className="font-label-caps-micro uppercase text-on-surface-variant">{name}</span><div className="text-4xl mt-space-md">{value}</div></div>)}</div><section className="mt-space-xl bg-surface-container-lowest p-space-xl rounded-xl shadow-sm"><h2 className="font-headline-md">Regional Geo-Spatial Risk Matrix</h2><p className="font-body-sm text-on-surface-variant mt-space-xs">Current source: local route segments. Replace with backend aggregation when an endpoint is available.</p><div className="grid grid-cols-1 md:grid-cols-2 gap-space-md mt-space-lg">{segments.map(s=><Link to={`/segment/${s.segment_id}`} key={s.segment_id} className="p-space-md bg-surface-container-low rounded-DEFAULT flex justify-between"><span><MapPin size={15} className="inline text-secondary"/> {s.road_name}</span><b className={scoreTone(s.final_score).split(" ")[0]}>{s.final_score}/100</b></Link>)}</div></section></div></div>; }
